apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-arle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-arle
    app.kubernetes.io/part-of: test-app-ihfs
  name: test-component-arle
  namespace: build-e2e-uvvm-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-arle
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-arle
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:e2e8ee4c446781fbe5991f2495b77f64a48f18a0b7f80cd055d0618af50cf4d5
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
